objet1 = input('Digite qualquer coisa: ')
print('O tipo primitivo desse valor é ', type(objet1))
print('O valor é alfabético? ', objet1.isalpha())
print('O valor é número? ', objet1.isnumeric())
print('O valor é alfanumérico? ', objet1.isalnum())
print('Esta em Maiúsculas? ', objet1.isupper())
print('Está em minusculas? ', objet1.islower())
print('Está capitalizada? ', objet1.istitle())
print('Só tem espaços? ', objet1.isspace())
